dist: xenial

language: c

compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TbTVVcmerA7qH1XVEvHhIfal17PnDd3MSzb2PZ8G0ocydlqxgZijGkDwcYtRSUYGkFi7NZHYceM9XZRpkIK/xX9eZR8cvzGwSWmPaFaoUVdbDXHSQvCTMRQmDXEaecZXUXYplGqzduPbhgFl4vDJNLMnFvzwhGf9E7CSClkM7tY="

before_script: autoreconf -fi

script: ./configure --enable-ssl --enable-mysql --enable-pgsql --enable-sqlite --enable-db --enable-ldap --enable-pam --enable-pipe --enable-anon --enable-fs --without-subst && make && make check

addons:
  apt:
    update: true
    packages:
      - autoconf-archive
      - libssl-dev
      - libgsasl7-dev
      - libdb-dev
      - libpam0g-dev
      - libmysqlclient-dev
      - libpq-dev
      - libldap2-dev
      - libsqlite3-dev
      - libidn11-dev
      - libexpat1-dev
      - libudns-dev
      - check
  coverity_scan:
    project:
      name: "jabberd2/jabberd2"
      description: "Build submitted via Travis CI"
    notification_email: tomek@xiaoka.com
    build_command_prepend: "./configure --enable-ssl --enable-mysql --enable-pgsql --enable-sqlite --enable-db --enable-ldap --enable-pam --enable-pipe --enable-anon --enable-fs --without-subst"
    build_command: "make -j 4"
    branch_pattern: coverity_scan
